### Get all movie info
GET http://localhost:8081/api/v1/movie-info
Accept: application/json

### Get all movie info with pagination and multiple sorting criteria
GET http://localhost:8081/api/v1/movie-info/page?page=0&size=10&sortBy=movieId&sortBy=director&sortDirection=asc&sortDirection=asc
Accept: application/json

### Get all movie info with pagination, multiple sorting criteria, and filtering
GET http://localhost:8081/api/v1/movie-info/filter?page=0&size=10&sortBy=movieId&sortBy=director&sortDirection=asc&sortDirection=asc&director=Christopher%20Nolan&id=1
Accept: application/json

### Get all movies with pagination, multiple sorting criteria, and filtering with multiple values for the same column
GET http://localhost:8081/api/v1/movie-info/list-filter?page=0&size=10&sortBy=movieId&sortBy=director&sortDirection=asc&sortDirection=asc&director=Christopher%20Nolan&id=1,2
Accept: application/json
